In [1]:
import numpy as np
import pandas as pd
from random import random
from time import time
import os
from imbalanced.imblearn.over_sampling import SMOTE

In [6]:
start_time = time()

path = 'C:/Users/VIPLAB/Desktop/preprocess_py/'
filename = '0805_marketing_with_picked_group11_with_id.csv'

# cols = ['P3M_AVG_DATA_USAGE_MB', 'DATA_USAGE_MB', 'IMEI_MFG_NAME', 'L3M_DATA_USAGE_MB', 'IMEI_MKT_NAME', 'AGE', 'GENDER_CODE', 'DATA_MONTHLY_FEE', 'L3M_AVG_NET_INV_AMT', 'TOTAL_MONTHLY_FEE', 'L3M_NET_INV_AMT', 'PROM_CURR_PROMOTION_TYPE', 'DATA_INV_AMT', 'MOST_MT_OPERATOR', 'VOICE_INV_AMT', 'LAST_CHANNEL_TYPE', 'TENURE_SCV', 'BILL_CITY_NAME', 'BILL_ZIP_CODE', 'ACTV_STORE_ID', 'MOST_MO_OPERATOR', 'CURR_DATA_BILL_PLAN_NAME', 'BL_CYCLE_DESC', 'ZONE_ACTIVATION_IVR', 'MOC_TWM_CNT', 'P3M_MO_PSTN_CNT', 'MTC_TWM_CNT', 'PSTN_CNT', 'MTC_CHM_CNT', 'MOC_CHM_CNT', 'MOC_PSTN_CNT', 'MTC_PSTN_CNT', 'MT_PSTN_CNT', 'HS_CHG_CNT', 'SMS_PROM_IND', 'MTC_APT_CNT', 'L3M_AVG_SMS_INV_AMT', 'MULTI_SIM_INCLUDE_WBB', 'MOC_APT_CNT', 'MTC_DUR', 'MOC_TSC_CNT', 'MTC_TSC_CNT', 'PROM_FLAT_RATE_4G_IND', 'FLAT_RATE_4G_IND', 'MT_TTL_DURATION', 'MO_TTL_DURATION', 'MT_OFFNET_DUR', 'MT_ONNET_DUR', 'MTC_PSTN_DUR']

df = pd.read_csv(path + filename, error_bad_lines=False)

print('load csv %s seconds', format(time() - start_time))

C:\Users\VIPLAB\AppData\Local\conda\conda\envs\keras\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (26,72) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


load csv %s seconds 32.8895468711853


In [3]:
df['Groups'].value_counts()

InstantMessage-High                           354405
InstantMessage-SuperHigh                      313130
No_significant_preference                     309453
No_significant_preference(instant_message)    282471
Social-media                                  117312
Infrequent_User                               105121
Portal                                         86329
Game                                           80623
Lifestyle                                      72276
Adult                                          48285
Entertainment                                  42540
Name: Groups, dtype: int64

In [14]:
np.sum(df['Groups'].value_counts())

1811945

In [8]:
cols = ['P3M_AVG_DATA_USAGE_MB', 'DATA_USAGE_MB', 'IMEI_MFG_NAME', 'L3M_DATA_USAGE_MB', 'IMEI_MKT_NAME', 'AGE', 'GENDER_CODE', 'DATA_MONTHLY_FEE', 'L3M_AVG_NET_INV_AMT', 'TOTAL_MONTHLY_FEE', 'L3M_NET_INV_AMT', 'PROM_CURR_PROMOTION_TYPE', 'DATA_INV_AMT', 'MOST_MT_OPERATOR', 'VOICE_INV_AMT', 'LAST_CHANNEL_TYPE', 'TENURE_SCV', 'BILL_CITY_NAME', 'BILL_ZIP_CODE', 'ACTV_STORE_ID', 'MOST_MO_OPERATOR', 'CURR_DATA_BILL_PLAN_NAME', 'BL_CYCLE_DESC', 'ZONE_ACTIVATION_IVR', 'MOC_TWM_CNT', 'P3M_MO_PSTN_CNT', 'MTC_TWM_CNT', 'PSTN_CNT', 'MTC_CHM_CNT', 'MOC_CHM_CNT', 'MOC_PSTN_CNT', 'MTC_PSTN_CNT', 'MT_PSTN_CNT', 'HS_CHG_CNT', 'SMS_PROM_IND', 'MTC_APT_CNT', 'L3M_AVG_SMS_INV_AMT', 'MULTI_SIM_INCLUDE_WBB', 'MOC_APT_CNT', 'MTC_DUR', 'MOC_TSC_CNT', 'MTC_TSC_CNT', 'PROM_FLAT_RATE_4G_IND', 'FLAT_RATE_4G_IND', 'MT_TTL_DURATION', 'MO_TTL_DURATION', 'MT_OFFNET_DUR', 'MT_ONNET_DUR', 'MTC_PSTN_DUR']
df = df[cols]

In [26]:
df['BILL_ZIP_CODE'] = df['BILL_ZIP_CODE'].astype(str)

In [28]:
cate_cols = []
for c in df.columns:
    if df[c].dtype == np.object:
        print(df[c].value_counts())
        cate_cols.append(c)

H    785226
M    764537
L    262182
Name: DATA_USAGE_MB, dtype: int64
Apple                                                                                                                                                     629046
SAMSUNG                                                                                                                                                   434406
HTC                                                                                                                                                       226531
ASUS                                                                                                                                                      165111
Sony                                                                                                                                                      128054
OPPO                                                                                                                         

Name: IMEI_MKT_NAME, Length: 1867, dtype: int64
M    909967
F    896944
0      5034
Name: GENDER_CODE, dtype: int64
4G SMP                  629544
4G iPhone               264506
4G Student/anti         199714
50%V+499                170446
4G SIMalone              88937
Data Non-flat with d     83375
4G 499                   65344
4G Student               44747
4G Low Rate              41044
SIM Alone                37187
Tablet                   36668
Non Flat Rate            35993
Antichurn SIM            31458
others                   20156
4G Low rate              19822
Data flat with dis.       6440
Plan B                    5721
SIM                       5715
Home WiFi                 4123
V+499                     2802
SIM alone                 2652
iPhone                    2150
iPad                      2150
50% Off                   1818
BAU HS                    1565
90% Off                   1220
Antichurn Tablet          1212
Pre to Post               1199
PBB             

In [31]:
cate_cols

['DATA_USAGE_MB',
 'IMEI_MFG_NAME',
 'IMEI_MKT_NAME',
 'GENDER_CODE',
 'PROM_CURR_PROMOTION_TYPE',
 'MOST_MT_OPERATOR',
 'LAST_CHANNEL_TYPE',
 'BILL_CITY_NAME',
 'BILL_ZIP_CODE',
 'ACTV_STORE_ID',
 'MOST_MO_OPERATOR',
 'CURR_DATA_BILL_PLAN_NAME',
 'BL_CYCLE_DESC',
 'ZONE_ACTIVATION_IVR',
 'SMS_PROM_IND',
 'MTC_DUR',
 'PROM_FLAT_RATE_4G_IND',
 'FLAT_RATE_4G_IND']

In [41]:
des = df.describe().iloc[2]

In [48]:
des['AGE']

13.603822641194006

In [38]:
des['AGE'][4] - des["AGE"][5]

-9.0

In [49]:
def in_distance(row_a, row_b, all_cols, cate_cols, std):
    for c in all_cols:
        if not c in cate_cols:
            if abs(row_a[c] - row_b[c]) >= std[c]:
                return False
    return True

In [ ]:
def oversample_cate()

In [51]:
df['AGE'][]

SyntaxError: invalid syntax (<ipython-input-51-26db2d1115e2>, line 1)

In [52]:
from random import sample

In [53]:
X = []
y = []
for i in range(30):
    X.append(sample(range(50), 5))
    y.append('A' if random() > 0.65 else 'B')

In [54]:
a_count = 0
b_count = 0
for i in range(len(X)):
    if y[i] == 'A':
        a_count += 1
    else:
        b_count += 1
    print(X[i], y[i])
print("A:", a_count)
print("B:", b_count)

[20, 6, 36, 0, 31] B
[6, 15, 2, 39, 35] A
[2, 11, 41, 7, 5] B
[8, 47, 30, 42, 2] A
[47, 43, 24, 34, 28] A
[16, 46, 6, 40, 23] B
[39, 46, 34, 22, 21] A
[39, 4, 29, 11, 43] B
[17, 29, 49, 15, 25] B
[36, 22, 40, 17, 3] B
[20, 38, 28, 15, 4] B
[33, 45, 3, 20, 46] B
[17, 46, 7, 32, 8] B
[28, 49, 36, 17, 16] B
[21, 6, 4, 2, 12] B
[29, 6, 17, 32, 23] A
[33, 42, 17, 6, 25] B
[38, 31, 36, 6, 30] A
[30, 37, 25, 14, 36] A
[16, 26, 2, 3, 34] B
[9, 15, 31, 42, 39] A
[35, 13, 3, 46, 20] B
[7, 13, 27, 42, 21] B
[7, 2, 13, 38, 14] B
[37, 30, 0, 7, 49] B
[25, 27, 47, 28, 26] B
[27, 21, 19, 48, 25] A
[41, 6, 25, 47, 1] B
[13, 20, 18, 47, 40] A
[30, 48, 29, 14, 46] B
A: 10
B: 20


In [57]:
sm = SMOTE(random_state=42, n_jobs=-1)
sm.fit(X, y)
sm_x, sm_y = sm.sample(X, y)

In [58]:
for i in range(len(sm_x)):
    print(sm_x[i], sm_y[i])

[ 20.   6.  36.   0.  31.] B
[  6.  15.   2.  39.  35.] A
[  2.  11.  41.   7.   5.] B
[  8.  47.  30.  42.   2.] A
[ 47.  43.  24.  34.  28.] A
[ 16.  46.   6.  40.  23.] B
[ 39.  46.  34.  22.  21.] A
[ 39.   4.  29.  11.  43.] B
[ 17.  29.  49.  15.  25.] B
[ 36.  22.  40.  17.   3.] B
[ 20.  38.  28.  15.   4.] B
[ 33.  45.   3.  20.  46.] B
[ 17.  46.   7.  32.   8.] B
[ 28.  49.  36.  17.  16.] B
[ 21.   6.   4.   2.  12.] B
[ 29.   6.  17.  32.  23.] A
[ 33.  42.  17.   6.  25.] B
[ 38.  31.  36.   6.  30.] A
[ 30.  37.  25.  14.  36.] A
[ 16.  26.   2.   3.  34.] B
[  9.  15.  31.  42.  39.] A
[ 35.  13.   3.  46.  20.] B
[  7.  13.  27.  42.  21.] B
[  7.   2.  13.  38.  14.] B
[ 37.  30.   0.   7.  49.] B
[ 25.  27.  47.  28.  26.] B
[ 27.  21.  19.  48.  25.] A
[ 41.   6.  25.  47.   1.] B
[ 13.  20.  18.  47.  40.] A
[ 30.  48.  29.  14.  46.] B
[  6.47034301  14.81595274   2.30674544  38.85685213  34.75460365] A
[  8.54186556  29.66030198  30.54186556  42.          22.0490

In [4]:
start_time = time()

path = 'D:/0805_sample_SMOTE/Adult/'
filename = '0805_marketing_with_picked_group11_numeric_max_min_sample_Adult_others.csv'

# cols = ['P3M_AVG_DATA_USAGE_MB', 'DATA_USAGE_MB', 'IMEI_MFG_NAME', 'L3M_DATA_USAGE_MB', 'IMEI_MKT_NAME', 'AGE', 'GENDER_CODE', 'DATA_MONTHLY_FEE', 'L3M_AVG_NET_INV_AMT', 'TOTAL_MONTHLY_FEE', 'L3M_NET_INV_AMT', 'PROM_CURR_PROMOTION_TYPE', 'DATA_INV_AMT', 'MOST_MT_OPERATOR', 'VOICE_INV_AMT', 'LAST_CHANNEL_TYPE', 'TENURE_SCV', 'BILL_CITY_NAME', 'BILL_ZIP_CODE', 'ACTV_STORE_ID', 'MOST_MO_OPERATOR', 'CURR_DATA_BILL_PLAN_NAME', 'BL_CYCLE_DESC', 'ZONE_ACTIVATION_IVR', 'MOC_TWM_CNT', 'P3M_MO_PSTN_CNT', 'MTC_TWM_CNT', 'PSTN_CNT', 'MTC_CHM_CNT', 'MOC_CHM_CNT', 'MOC_PSTN_CNT', 'MTC_PSTN_CNT', 'MT_PSTN_CNT', 'HS_CHG_CNT', 'SMS_PROM_IND', 'MTC_APT_CNT', 'L3M_AVG_SMS_INV_AMT', 'MULTI_SIM_INCLUDE_WBB', 'MOC_APT_CNT', 'MTC_DUR', 'MOC_TSC_CNT', 'MTC_TSC_CNT', 'PROM_FLAT_RATE_4G_IND', 'FLAT_RATE_4G_IND', 'MT_TTL_DURATION', 'MO_TTL_DURATION', 'MT_OFFNET_DUR', 'MT_ONNET_DUR', 'MTC_PSTN_DUR']

df_smote_adult = pd.read_csv(path + filename, error_bad_lines=False)

print('load csv %s seconds', format(time() - start_time))

load csv %s seconds 96.16406106948853


In [25]:
df_smote_adult['Groups'].value_counts()

Others    1763660
Adult     1763660
Name: Groups, dtype: int64

In [51]:
df_smote_adult["GENDER_CODE"].iloc[0:1811956].value_counts()

0.5    909973
0.0    896949
1.0      5034
Name: GENDER_CODE, dtype: int64

In [10]:
1763660 - 1731322

32338

In [7]:
start_time = time()

path = 'D:/0805_sample_SMOTE/Game/'
filename = '0805_marketing_with_picked_group11_numeric_max_min_sample_Game_others.csv'

# cols = ['P3M_AVG_DATA_USAGE_MB', 'DATA_USAGE_MB', 'IMEI_MFG_NAME', 'L3M_DATA_USAGE_MB', 'IMEI_MKT_NAME', 'AGE', 'GENDER_CODE', 'DATA_MONTHLY_FEE', 'L3M_AVG_NET_INV_AMT', 'TOTAL_MONTHLY_FEE', 'L3M_NET_INV_AMT', 'PROM_CURR_PROMOTION_TYPE', 'DATA_INV_AMT', 'MOST_MT_OPERATOR', 'VOICE_INV_AMT', 'LAST_CHANNEL_TYPE', 'TENURE_SCV', 'BILL_CITY_NAME', 'BILL_ZIP_CODE', 'ACTV_STORE_ID', 'MOST_MO_OPERATOR', 'CURR_DATA_BILL_PLAN_NAME', 'BL_CYCLE_DESC', 'ZONE_ACTIVATION_IVR', 'MOC_TWM_CNT', 'P3M_MO_PSTN_CNT', 'MTC_TWM_CNT', 'PSTN_CNT', 'MTC_CHM_CNT', 'MOC_CHM_CNT', 'MOC_PSTN_CNT', 'MTC_PSTN_CNT', 'MT_PSTN_CNT', 'HS_CHG_CNT', 'SMS_PROM_IND', 'MTC_APT_CNT', 'L3M_AVG_SMS_INV_AMT', 'MULTI_SIM_INCLUDE_WBB', 'MOC_APT_CNT', 'MTC_DUR', 'MOC_TSC_CNT', 'MTC_TSC_CNT', 'PROM_FLAT_RATE_4G_IND', 'FLAT_RATE_4G_IND', 'MT_TTL_DURATION', 'MO_TTL_DURATION', 'MT_OFFNET_DUR', 'MT_ONNET_DUR', 'MTC_PSTN_DUR']

df_smote_game = pd.read_csv(path + filename, error_bad_lines=False)

print('load csv %s seconds', format(time() - start_time))

load csv %s seconds 96.86961650848389


In [9]:
df_smote_game['Groups'].value_counts()

Others    1731322
Game      1731322
Name: Groups, dtype: int64

In [32]:
start_time = time()

path = ''
filename = 'Groups_ID_10_catg_0805.csv'

# cols = ['P3M_AVG_DATA_USAGE_MB', 'DATA_USAGE_MB', 'IMEI_MFG_NAME', 'L3M_DATA_USAGE_MB', 'IMEI_MKT_NAME', 'AGE', 'GENDER_CODE', 'DATA_MONTHLY_FEE', 'L3M_AVG_NET_INV_AMT', 'TOTAL_MONTHLY_FEE', 'L3M_NET_INV_AMT', 'PROM_CURR_PROMOTION_TYPE', 'DATA_INV_AMT', 'MOST_MT_OPERATOR', 'VOICE_INV_AMT', 'LAST_CHANNEL_TYPE', 'TENURE_SCV', 'BILL_CITY_NAME', 'BILL_ZIP_CODE', 'ACTV_STORE_ID', 'MOST_MO_OPERATOR', 'CURR_DATA_BILL_PLAN_NAME', 'BL_CYCLE_DESC', 'ZONE_ACTIVATION_IVR', 'MOC_TWM_CNT', 'P3M_MO_PSTN_CNT', 'MTC_TWM_CNT', 'PSTN_CNT', 'MTC_CHM_CNT', 'MOC_CHM_CNT', 'MOC_PSTN_CNT', 'MTC_PSTN_CNT', 'MT_PSTN_CNT', 'HS_CHG_CNT', 'SMS_PROM_IND', 'MTC_APT_CNT', 'L3M_AVG_SMS_INV_AMT', 'MULTI_SIM_INCLUDE_WBB', 'MOC_APT_CNT', 'MTC_DUR', 'MOC_TSC_CNT', 'MTC_TSC_CNT', 'PROM_FLAT_RATE_4G_IND', 'FLAT_RATE_4G_IND', 'MT_TTL_DURATION', 'MO_TTL_DURATION', 'MT_OFFNET_DUR', 'MT_ONNET_DUR', 'MTC_PSTN_DUR']

df_group = pd.read_csv(path + filename, error_bad_lines=False)

print('load csv %s seconds', format(time() - start_time))

load csv %s seconds 0.643989086151123


In [21]:
df_group['Groups'].value_counts()

InstantMessage-High                           354353
InstantMessage-SuperHigh                      313064
No_significant_preference                     309395
No_significant_preference(instant_message)    282425
Social-media                                  117289
Infrequent_User                               105080
Portal                                         86320
Game                                           80610
Lifestyle                                      72266
Adult                                          48282
Entertainment                                  42531
Name: Groups, dtype: int64

In [22]:
np.sum(df_group['Groups'].value_counts()) - 48282

1763333

In [19]:
80610 - 48282

32328

In [11]:
no1 = df['MINING_DW_SUBSCR_NO'].values
no2 = df_group['MINING_DW_SUBSCR_NO'].values

In [5]:
no1.sort()

In [6]:
no2.sort()

In [12]:
len(no1) - len(no2)

-326

In [15]:
len(no2)

1811615

In [8]:
f1 = 0
f2 = 0
diff = []
for i in range(len(no1)):
    if no1[f1] == no2[f2]:
        f1 += 1
        f2 += 1
    elif no1[f1] > no2[f2]:
        diff.append(no2[f2])
        f2 += 1
    else:
        diff.append(no1[f1])
        f1 += 1
diff


[11696539,
 111087914,
 112836011,
 112986720,
 113357577,
 113870811,
 113955844,
 115934077,
 116369874,
 117633726,
 117633726,
 117737962,
 118180357,
 119277116,
 119498113,
 1110841675,
 1110866764,
 1111032530,
 1111274289,
 1114190192,
 1114247300,
 1115464254,
 1117611634,
 2113719137,
 2113755138,
 2114080758,
 2114540893,
 2114694124,
 2115017761,
 2115150986,
 2115268942,
 2115383927,
 2115498157,
 2115941678,
 2116066091,
 2116115075,
 2116312485,
 2116394218,
 2116403642,
 2116651650,
 2116897956,
 2116940644,
 2117156779,
 2117168120,
 2117812307,
 2118277920,
 2118427817,
 2119164376,
 3113224782,
 3114360404,
 3114361117,
 3114641980,
 3114932551,
 3115253964,
 3115661199,
 3116197215,
 3116216592,
 3116266634,
 3116292468,
 3116300456,
 3116554262,
 3116596523,
 3116765261,
 3116784253,
 3117303302,
 3117687043,
 3117814302,
 3118306634,
 3118331805,
 3118751461,
 3118907549,
 3119001157,
 3119173412,
 3119204777,
 3119216004,
 3119493641,
 3119626112,
 3119708494,
 3

In [9]:
len(diff)

330

In [10]:
for d in diff:
    df = df[df['MINING_DW_SUBSCR_NO'] != d]

In [13]:
df['Groups'].value_counts()

InstantMessage-High                           354280
InstantMessage-SuperHigh                      313003
No_significant_preference                     309350
No_significant_preference(instant_message)    282363
Social-media                                  117263
Infrequent_User                               105086
Portal                                         86299
Game                                           80594
Lifestyle                                      72258
Adult                                          48263
Entertainment                                  42530
Name: Groups, dtype: int64

In [15]:
vc = df['MINING_DW_SUBSCR_NO'].value_counts()
vc

In [17]:
vc2 = df_group['MINING_DW_SUBSCR_NO'].value_counts()
vc2

3128952831     1
3118420316     1
3131023682     1
3126825284     1
3123803817     1
3118434631     1
10000700984    1
8134846795     1
3114254670     1
3118283997     1
3122602322     1
3130527694     1
3126819161     1
8131092690     1
3122413886     1
10001079227    1
3126763874     1
8134758756     1
3122567525     1
10000715093    1
3126778221     1
8134699625     1
3135115636     1
8130533749     1
111018358      1
8131218528     1
3126833472     1
10001076540    1
2115111159     1
3134393138     1
              ..
8131711838     1
3123714911     1
8136160034     1
3124123066     1
3128156960     1
8136033052     1
3124501215     1
1115548385     1
8136817379     1
8136999734     1
1110066692     1
3128808166     1
8136794856     1
3124603625     1
3128158965     1
8136792815     1
2113759985     1
8132569849     1
3137155834     1
3137243781     1
2113739519     1
3119698694     1
3123884810     1
8133314021     1
8131869459     1
8136053526     1
8131861271     1
8136043289    

In [7]:
df = df[['MINING_DW_SUBSCR_NO', 'BOOSTER_AMT', 'L3M_AVG_NET_INV_AMT', 'L3M_AVG_SMS_INV_AMT', 'PAY_PENALTY_AMT', 'TOTAL_MONTHLY_FEE', 'VOICE_MONTHLY_FEE', 'CWC_CATG1_CNT', 'CWC_CATG10_CNT', 'CWC_CATG11_CNT', 'CWC_CATG12_CNT', 'CWC_CATG13_CNT', 'CWC_CATG2_CNT', 'CWC_CATG3_CNT', 'CWC_CATG4_CNT', 'CWC_CATG5_CNT', 'CWC_CATG6_CNT', 'CWC_CATG7_CNT', 'CWC_CATG8_CNT', 'CWC_CATG9_CNT', 'SELFCARE_IND', 'LAST_CHANNEL_TYPE', 'AVG_HS_USE_MONTH_EX_CURR', 'HS_LEASE_FEATURE_NAME', 'IMEI_MFG_NAME', 'IMEI_MKT_NAME', 'ACTV_TYPE', 'AGE', 'APPLY_CURR_EBILL_SBILL_FLAG', 'AUTOPAY_IND', 'BILL_ZIP_CODE', 'CHANNEL_CHURN_INDEX', 'CHURN_CLM_IND', 'CURR_DATA_BILL_PLAN_NAME', 'CURR_PROM_COMMIT_MONTHS', 'CUST_TYPE', 'DATA_MONTHLY_FEE', 'FETNET_IND', 'FLAT_RATE_3G_IND', 'FLAT_RATE_4G_IND', 'GA_IND', 'GENDER_CODE', 'GOOGLE_PLAY_IND', 'HAPPYGO_IND', 'MDS_CURR_RENEW_CNT', 'MDS_CURR_RENEW_TYPE', 'MSISDN_LAST_NP_OUT_IND', 'NP_IN_IND', 'ORIG_OPR_ID', 'PAY_PENALTY_FLAG', 'PROM_CURR_EXP_MONTH_CNT', 'PROM_CURR_PROMOTION_SUB_TYPE', 'PROM_CURR_PROMOTION_TYPE', 'PROM_FLAT_RATE_4G_IND', 'SERVICE_STATUS_MOVIE_FLAG', 'SERVICE_STATUS_OMUSIC_FLAG', 'SERVICE_STATUS_READING_FLAG', 'SRV_TYPE_DESC', 'TENURE_SCV', 'VIP_GRADE', 'VIP_REDEEM_IND', 'VIP_TENURE', 'ZONE_ACTIVATION_IVR', 'DATA_BOOSTER_EVER_USE_FLAG', 'MOC_APT_CNT', 'MOC_APT_DUR', 'MOC_CHM_CNT', 'MOC_CHM_DUR', 'MOC_TSC_CNT', 'MOC_TSC_DUR', 'MOC_TWM_CNT', 'MOC_TWM_DUR', 'MOST_MO_OPERATOR', 'MOST_MT_OPERATOR', 'MTC_APT_CNT', 'MTC_APT_DUR', 'MTC_CHM_CNT', 'MTC_CHM_DUR', 'MTC_TSC_CNT', 'MTC_TSC_DUR', 'MTC_TWM_CNT', 'MTC_TWM_DUR', 'P3M_AVG_DATA_USAGE_MB', 'Groups']]

In [8]:
df

MINING_DW_SUBSCR_NO  BOOSTER_AMT  L3M_AVG_NET_INV_AMT  \
0                 2118544651          0.0               501.77   
1                10000337216          0.0              1441.63   
2                 3133428916          0.0               703.14   
3                 3135493626          0.0               715.16   
4                 3125061767          0.0               673.72   
5                 8131713026          0.0              1444.92   
6                 3117930663          0.0               504.00   
7                 3133731219          0.0              1120.10   
8                10000354353          0.0               771.26   
9                 3136438041          0.0               299.00   
10                8135618387          0.0               149.00   
11                8136932676          0.0              1020.47   
12                3128800944          0.0               528.27   
13                3116365482          0.0              1311.39   
14                3116484464          0.0              1856.23   
15                3114599843          0.0              1446.37   
16                3123106343          0.0              1310.55   
17                3119251416          0.0              1114.64   
18               10000055282          0.0              1012.47   
19                3125730712          0.0                49.00   
20                3128807408          0.0              1204.24   
21                3119085232          0.0              1433.62   
22                 116516819          0.0              1213.57   
23               10000639519          0.0               796.99   
24                8133716629          0.0               636.33   
25                8135353590          0.0              1018.97   
26               10000147431          0.0               729.66   
27                8135170269          0.0              2749.95   
28               10000327520          0.0              1296.74   
29                3130746672          0.0               707.92   
...                      ...          ...                  ...   
1811915           3126452045          0.0              1493.67   
1811916           3114379993          0.0              1298.10   
1811917           1110232808          0.0               702.60   
1811918           3136945011          0.0               836.52   
1811919          10000389604          0.0               599.75   
1811920           8131588557          0.0               599.00   
1811921           3126958038          0.0              1441.37   
1811922           2113652859          0.0               656.99   
1811923            112931875          0.0              1689.50   
1811924           8135000853          0.0              1000.33   
1811925           8134430521          0.0              1411.16   
1811926           3126380265          0.0              1609.17   
1811927          10000986769          0.0               532.07   
1811928           3126624693          0.0               811.40   
1811929           3116861779          0.0              1423.47   
1811930           8132467656          0.0               599.00   
1811931           3122634624          0.0              1978.56   
1811932           3137015814          0.0               336.81   
1811933           8135931363          0.0               526.00   
1811934          10000460407          0.0               714.19   
1811935           3127456590          0.0               803.97   
1811936           3132074866          0.0               599.00   
1811937          10000949263          0.0              2465.23   
1811938           3127741756          0.0              1007.44   
1811939           3121442549          0.0               310.63   
1811940           8134942978          0.0              1328.03   
1811941           3118630650          0.0               865.87   
1811942           1110024909          0.0               700.26   
1811943           8133951361          0.0        

In [24]:
cate_cols = []
num_cols = []
for c in df.columns:
    if df[c].dtype == np.object:
        print(c)
        cate_cols.append(c)
    else:
        num_cols.append(c)

SELFCARE_IND
LAST_CHANNEL_TYPE
HS_LEASE_FEATURE_NAME
IMEI_MFG_NAME
IMEI_MKT_NAME
ACTV_TYPE
APPLY_CURR_EBILL_SBILL_FLAG
AUTOPAY_IND
BILL_ZIP_CODE
CHANNEL_CHURN_INDEX
CHURN_CLM_IND
CURR_DATA_BILL_PLAN_NAME
CURR_PROM_COMMIT_MONTHS
CUST_TYPE
FETNET_IND
FLAT_RATE_3G_IND
FLAT_RATE_4G_IND
GA_IND
GENDER_CODE
GOOGLE_PLAY_IND
HAPPYGO_IND
MDS_CURR_RENEW_TYPE
MSISDN_LAST_NP_OUT_IND
NP_IN_IND
ORIG_OPR_ID
PAY_PENALTY_FLAG
PROM_CURR_PROMOTION_SUB_TYPE
PROM_CURR_PROMOTION_TYPE
PROM_FLAT_RATE_4G_IND
SERVICE_STATUS_MOVIE_FLAG
SERVICE_STATUS_OMUSIC_FLAG
SERVICE_STATUS_READING_FLAG
SRV_TYPE_DESC
VIP_GRADE
VIP_REDEEM_IND
ZONE_ACTIVATION_IVR
DATA_BOOSTER_EVER_USE_FLAG
MOST_MO_OPERATOR
MOST_MT_OPERATOR


In [9]:
start_time = time()

path = 'D:/NEW_DATA_FULL_2017_8_14/'
filename = 'DM_SUBSCR_MOC_AVG_MLY.txt'

# cols = ['P3M_AVG_DATA_USAGE_MB', 'DATA_USAGE_MB', 'IMEI_MFG_NAME', 'L3M_DATA_USAGE_MB', 'IMEI_MKT_NAME', 'AGE', 'GENDER_CODE', 'DATA_MONTHLY_FEE', 'L3M_AVG_NET_INV_AMT', 'TOTAL_MONTHLY_FEE', 'L3M_NET_INV_AMT', 'PROM_CURR_PROMOTION_TYPE', 'DATA_INV_AMT', 'MOST_MT_OPERATOR', 'VOICE_INV_AMT', 'LAST_CHANNEL_TYPE', 'TENURE_SCV', 'BILL_CITY_NAME', 'BILL_ZIP_CODE', 'ACTV_STORE_ID', 'MOST_MO_OPERATOR', 'CURR_DATA_BILL_PLAN_NAME', 'BL_CYCLE_DESC', 'ZONE_ACTIVATION_IVR', 'MOC_TWM_CNT', 'P3M_MO_PSTN_CNT', 'MTC_TWM_CNT', 'PSTN_CNT', 'MTC_CHM_CNT', 'MOC_CHM_CNT', 'MOC_PSTN_CNT', 'MTC_PSTN_CNT', 'MT_PSTN_CNT', 'HS_CHG_CNT', 'SMS_PROM_IND', 'MTC_APT_CNT', 'L3M_AVG_SMS_INV_AMT', 'MULTI_SIM_INCLUDE_WBB', 'MOC_APT_CNT', 'MTC_DUR', 'MOC_TSC_CNT', 'MTC_TSC_CNT', 'PROM_FLAT_RATE_4G_IND', 'FLAT_RATE_4G_IND', 'MT_TTL_DURATION', 'MO_TTL_DURATION', 'MT_OFFNET_DUR', 'MT_ONNET_DUR', 'MTC_PSTN_DUR']

df1 = pd.read_csv(path + filename, error_bad_lines=False)

print('load csv %s seconds', format(time() - start_time))

load csv %s seconds 3.8224494457244873


In [10]:
start_time = time()

path = 'D:/NEW_DATA_FULL_2017_8_14/'
filename = 'DM_SUBSCR_MTC_AVG_MLY.txt'

# cols = ['P3M_AVG_DATA_USAGE_MB', 'DATA_USAGE_MB', 'IMEI_MFG_NAME', 'L3M_DATA_USAGE_MB', 'IMEI_MKT_NAME', 'AGE', 'GENDER_CODE', 'DATA_MONTHLY_FEE', 'L3M_AVG_NET_INV_AMT', 'TOTAL_MONTHLY_FEE', 'L3M_NET_INV_AMT', 'PROM_CURR_PROMOTION_TYPE', 'DATA_INV_AMT', 'MOST_MT_OPERATOR', 'VOICE_INV_AMT', 'LAST_CHANNEL_TYPE', 'TENURE_SCV', 'BILL_CITY_NAME', 'BILL_ZIP_CODE', 'ACTV_STORE_ID', 'MOST_MO_OPERATOR', 'CURR_DATA_BILL_PLAN_NAME', 'BL_CYCLE_DESC', 'ZONE_ACTIVATION_IVR', 'MOC_TWM_CNT', 'P3M_MO_PSTN_CNT', 'MTC_TWM_CNT', 'PSTN_CNT', 'MTC_CHM_CNT', 'MOC_CHM_CNT', 'MOC_PSTN_CNT', 'MTC_PSTN_CNT', 'MT_PSTN_CNT', 'HS_CHG_CNT', 'SMS_PROM_IND', 'MTC_APT_CNT', 'L3M_AVG_SMS_INV_AMT', 'MULTI_SIM_INCLUDE_WBB', 'MOC_APT_CNT', 'MTC_DUR', 'MOC_TSC_CNT', 'MTC_TSC_CNT', 'PROM_FLAT_RATE_4G_IND', 'FLAT_RATE_4G_IND', 'MT_TTL_DURATION', 'MO_TTL_DURATION', 'MT_OFFNET_DUR', 'MT_ONNET_DUR', 'MTC_PSTN_DUR']

df2 = pd.read_csv(path + filename, error_bad_lines=False)

print('load csv %s seconds', format(time() - start_time))

load csv %s seconds 3.698906660079956


In [11]:
start_time = time()

path = 'D:/NEW_DATA_FULL_2017_8_14/'
filename = 'mds_BILL_AVG_APR.txt'

# cols = ['P3M_AVG_DATA_USAGE_MB', 'DATA_USAGE_MB', 'IMEI_MFG_NAME', 'L3M_DATA_USAGE_MB', 'IMEI_MKT_NAME', 'AGE', 'GENDER_CODE', 'DATA_MONTHLY_FEE', 'L3M_AVG_NET_INV_AMT', 'TOTAL_MONTHLY_FEE', 'L3M_NET_INV_AMT', 'PROM_CURR_PROMOTION_TYPE', 'DATA_INV_AMT', 'MOST_MT_OPERATOR', 'VOICE_INV_AMT', 'LAST_CHANNEL_TYPE', 'TENURE_SCV', 'BILL_CITY_NAME', 'BILL_ZIP_CODE', 'ACTV_STORE_ID', 'MOST_MO_OPERATOR', 'CURR_DATA_BILL_PLAN_NAME', 'BL_CYCLE_DESC', 'ZONE_ACTIVATION_IVR', 'MOC_TWM_CNT', 'P3M_MO_PSTN_CNT', 'MTC_TWM_CNT', 'PSTN_CNT', 'MTC_CHM_CNT', 'MOC_CHM_CNT', 'MOC_PSTN_CNT', 'MTC_PSTN_CNT', 'MT_PSTN_CNT', 'HS_CHG_CNT', 'SMS_PROM_IND', 'MTC_APT_CNT', 'L3M_AVG_SMS_INV_AMT', 'MULTI_SIM_INCLUDE_WBB', 'MOC_APT_CNT', 'MTC_DUR', 'MOC_TSC_CNT', 'MTC_TSC_CNT', 'PROM_FLAT_RATE_4G_IND', 'FLAT_RATE_4G_IND', 'MT_TTL_DURATION', 'MO_TTL_DURATION', 'MT_OFFNET_DUR', 'MT_ONNET_DUR', 'MTC_PSTN_DUR']

df3 = pd.read_csv(path + filename, error_bad_lines=False)

print('load csv %s seconds', format(time() - start_time))

load csv %s seconds 2.5689756870269775


In [14]:
full_df = pd.merge(df, df1, on='MINING_DW_SUBSCR_NO', how='left')

In [50]:
full_df = pd.merge(full_df, df2, on='MINING_DW_SUBSCR_NO', how='left')

In [51]:
full_df = pd.merge(full_df, df3, on='MINING_DW_SUBSCR_NO', how='left')

In [26]:
full_df['DATA_MONTH'].unique()

array(['2017/4/1', nan], dtype=object)

In [46]:
len(full_df[full_df['DATA_MONTH'] != '2017/4/1'])

50199

In [48]:
na_id = full_df[full_df['DATA_MONTH'] != '2017/4/1']['MINING_DW_SUBSCR_NO'].values

In [49]:
for idd in na_id:
    if not idd in df_group['MINING_DW_SUBSCR_NO'].values:
        print(idd)

In [19]:
len(full_df)

1811945

In [20]:
len(df)

1811945

In [21]:
df1['DATA_MONTH'].value_counts()

2017/4/1    5839858
Name: DATA_MONTH, dtype: int64

In [73]:
len(df3)

6066224

In [76]:
df1.columns

Index(['DATA_MONTH', 'MINING_DW_SUBSCR_NO', 'L3M_AVG_MO_TTL_CNT',
       'L3M_AVG_MO_TTL_DUR', 'L3M_AVG_MO_ONNET_CNT', 'L3M_AVG_MO_ONNET_DUR',
       'L3M_AVG_MO_OFFNET_CNT', 'L3M_AVG_MO_OFFNET_DUR', 'L3M_AVG_MO_PSTN_CNT',
       'L3M_AVG_MO_PSTN_DUR'],
      dtype='object')

In [64]:
date_col = ['DATA_MONTH_x', 'DATA_MONTH_y', 'DATA_MONTH']
full_df.drop(date_col, 1, inplace=True)

In [67]:
full_df['Groups'].value_counts()

InstantMessage-High                           354405
InstantMessage-SuperHigh                      313130
No_significant_preference                     309453
No_significant_preference(instant_message)    282471
Social-media                                  117312
Infrequent_User                               105121
Portal                                         86329
Game                                           80623
Lifestyle                                      72276
Adult                                          48285
Entertainment                                  42540
Name: Groups, dtype: int64

In [80]:
# full_df.isnull().sum()  
# full_df[['L3M_AVG_MO_TTL_CNT','L3M_AVG_MO_TTL_DUR', 'L3M_AVG_MO_ONNET_CNT', 'L3M_AVG_MO_ONNET_DUR','L3M_AVG_MO_OFFNET_CNT', 'L3M_AVG_MO_OFFNET_DUR', 'L3M_AVG_MO_PSTN_CNT','L3M_AVG_MO_PSTN_DUR']][full_df['L3M_AVG_MO_TTL_DUR'] == 0]
full_df[full_df['L3M_AVG_MO_ONNET_DUR'] == 0]


MINING_DW_SUBSCR_NO  BOOSTER_AMT  L3M_AVG_NET_INV_AMT  \
0                 2118544651          0.0               501.77   
24                8133716629          0.0               636.33   
43                8136508159          0.0               514.10   
50                3128002344          0.0               999.20   
53                3136223678          0.0               764.52   
58                8136002166          0.0               499.00   
104               8134979507          0.0              1036.46   
108               2117634510          0.0               639.67   
112               3130389726          0.0               299.00   
123               3115947429          0.0                30.00   
135               8135876720          0.0               599.00   
140               3136186172          0.0               815.86   
156               3133673344          0.0               564.82   
165                112434601          0.0               539.24   
230               3116015000          0.0              1013.23   
235               3127635702        350.0               850.87   
240               8136569266          0.0               719.24   
245               8133930015          0.0               604.13   
247               3133615469          0.0               302.74   
248               3135363971          0.0               702.67   
257               3123659538          0.0               815.71   
281               3129017562          0.0               599.00   
343               3126348246          0.0               652.95   
382              10000496936          0.0               699.86   
400               8133688819          0.0               309.91   
422               3126789900          0.0               805.17   
427              10000700626          0.0               892.75   
471               8133223564          0.0              1399.00   
482               3124184923          0.0               507.27   
484               3124545101          0.0              1980.03   
...                      ...          ...                  ...   
1811600           3130449328          0.0               228.02   
1811603          10000155622          0.0               361.52   
1811608           3122051137          0.0              1230.20   
1811632           3116032887          0.0               599.00   
1811634           8131377199          0.0              1408.68   
1811655           8134822792          0.0               800.67   
1811659           8134971839          0.0               910.32   
1811682           2116573141          0.0                 0.00   
1811691           3135739105          0.0               510.83   
1811707           8135275420          0.0              1024.50   
1811709           8133594489          0.0               731.78   
1811750          10001062156          0.0               342.57   
1811753           3125100625          0.0               940.00   
1811755           3115337711          0.0                30.32   
1811756           3129718901          0.0               999.00   
1811762           3134625575          0.0               302.10   
1811768           8130403321          0.0               306.88   
1811772           3127483798          0.0               849.80   
1811803            119697990          0.0              1425.36   
1811807           3125648634          0.0              1051.07   
1811811           3134542145          0.0               504.00   
1811817           3136915622          0.0               719.92   
1811819           8131559168          0.0              1202.98   
1811840           3118808183          0.0               505.74   
1811880          10001022997          0.0               814.74   
1811892           3116174419          0.0               729.96   
1811893           8131780296          0.0              1006.36   
1811896            113775422         50.0                99.00   
1811917           1110232808          0.0        

In [98]:
start_time = time()

path = './'
filename = '0814_marketing_with_picked_group11_with_na_id.csv'

full_df = pd.read_csv(path + filename, error_bad_lines=False)

print('load csv %s seconds', format(time() - start_time))

C:\Users\VIPLAB\AppData\Local\conda\conda\envs\keras\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


load csv %s seconds 24.94022846221924


In [101]:
full_df['BILL_ZIP_CODE'] = full_df['BILL_ZIP_CODE'].astype(str)
full_df['BILL_ZIP_CODE'].unique()

array(['241', '807', '204', '231', '221', '545', '900', '407', '511',
       '730', '613', '428', '505', '106', '320', '832', '235', '701',
       '404', '908', '242', '813', '220', '266', '843', '330', '802',
       '950', '514', '234', '360', '411', '116', '328', '338', '911',
       '350', '712', '500', '264', '922', '251', '103', '112', '831',
       '508', '239', '236', '722', '702', '970', '806', '715', '326',
       '202', '400', '516', '926', '717', '800', '402', '973', '700',
       '824', '436', '600', '638', '269', '337', '523', '334', '437',
       '711', '203', '540', '335', '238', '302', '734', '110', '401',
       '621', '303', '403', '612', '111', '804', '300', '830', '104',
       '429', '515', '704', '206', '709', '406', '114', '408', '821',
       '414', '434', '716', '325', '427', '624', '333', '356', '708',
       '108', '725', '506', '503', '438', '115', '310', '324', '905',
       '829', '852', '205', '640', '433', '260', '826', '710', '833',
       '237', '307',

In [103]:
# move Groups to last column
cols = list(full_df.columns.values)
cols.remove('Groups')
cols.append('Groups')
full_df = full_df[cols]

In [104]:
full_df

MINING_DW_SUBSCR_NO  BOOSTER_AMT  L3M_AVG_NET_INV_AMT  \
0                 2118544651          0.0               501.77   
1                10000337216          0.0              1441.63   
2                 3133428916          0.0               703.14   
3                 3135493626          0.0               715.16   
4                 3125061767          0.0               673.72   
5                 8131713026          0.0              1444.92   
6                 3117930663          0.0               504.00   
7                 3133731219          0.0              1120.10   
8                10000354353          0.0               771.26   
9                 3136438041          0.0               299.00   
10                8135618387          0.0               149.00   
11                8136932676          0.0              1020.47   
12                3128800944          0.0               528.27   
13                3116365482          0.0              1311.39   
14                3116484464          0.0              1856.23   
15                3114599843          0.0              1446.37   
16                3123106343          0.0              1310.55   
17                3119251416          0.0              1114.64   
18               10000055282          0.0              1012.47   
19                3125730712          0.0                49.00   
20                3128807408          0.0              1204.24   
21                3119085232          0.0              1433.62   
22                 116516819          0.0              1213.57   
23               10000639519          0.0               796.99   
24                8133716629          0.0               636.33   
25                8135353590          0.0              1018.97   
26               10000147431          0.0               729.66   
27                8135170269          0.0              2749.95   
28               10000327520          0.0              1296.74   
29                3130746672          0.0               707.92   
...                      ...          ...                  ...   
1811915           3126452045          0.0              1493.67   
1811916           3114379993          0.0              1298.10   
1811917           1110232808          0.0               702.60   
1811918           3136945011          0.0               836.52   
1811919          10000389604          0.0               599.75   
1811920           8131588557          0.0               599.00   
1811921           3126958038          0.0              1441.37   
1811922           2113652859          0.0               656.99   
1811923            112931875          0.0              1689.50   
1811924           8135000853          0.0              1000.33   
1811925           8134430521          0.0              1411.16   
1811926           3126380265          0.0              1609.17   
1811927          10000986769          0.0               532.07   
1811928           3126624693          0.0               811.40   
1811929           3116861779          0.0              1423.47   
1811930           8132467656          0.0               599.00   
1811931           3122634624          0.0              1978.56   
1811932           3137015814          0.0               336.81   
1811933           8135931363          0.0               526.00   
1811934          10000460407          0.0               714.19   
1811935           3127456590          0.0               803.97   
1811936           3132074866          0.0               599.00   
1811937          10000949263          0.0              2465.23   
1811938           3127741756          0.0              1007.44   
1811939           3121442549          0.0               310.63   
1811940           8134942978          0.0              1328.03   
1811941           3118630650          0.0               865.87   
1811942           1110024909          0.0               700.26   
1811943           8133951361          0.0        

In [106]:
out_filename = "0814_marketing_with_picked_group11_with_na_id"
full_df.to_csv(out_filename + ".csv", index=False, encoding='utf-8')

In [107]:
full_df.isnull().sum()

MINING_DW_SUBSCR_NO                0
BOOSTER_AMT                        0
L3M_AVG_NET_INV_AMT                0
L3M_AVG_SMS_INV_AMT                0
PAY_PENALTY_AMT                    0
TOTAL_MONTHLY_FEE                  0
VOICE_MONTHLY_FEE                  0
CWC_CATG1_CNT                      0
CWC_CATG10_CNT                     0
CWC_CATG11_CNT                     0
CWC_CATG12_CNT                     0
CWC_CATG13_CNT                     0
CWC_CATG2_CNT                      0
CWC_CATG3_CNT                      0
CWC_CATG4_CNT                      0
CWC_CATG5_CNT                      0
CWC_CATG6_CNT                      0
CWC_CATG7_CNT                      0
CWC_CATG8_CNT                      0
CWC_CATG9_CNT                      0
SELFCARE_IND                       0
LAST_CHANNEL_TYPE                  0
AVG_HS_USE_MONTH_EX_CURR           0
HS_LEASE_FEATURE_NAME              0
IMEI_MFG_NAME                      0
IMEI_MKT_NAME                      0
ACTV_TYPE                          0
A

In [108]:
full_df.fillna(0, inplace=True)

In [109]:
full_df.isnull().sum()

MINING_DW_SUBSCR_NO            0
BOOSTER_AMT                    0
L3M_AVG_NET_INV_AMT            0
L3M_AVG_SMS_INV_AMT            0
PAY_PENALTY_AMT                0
TOTAL_MONTHLY_FEE              0
VOICE_MONTHLY_FEE              0
CWC_CATG1_CNT                  0
CWC_CATG10_CNT                 0
CWC_CATG11_CNT                 0
CWC_CATG12_CNT                 0
CWC_CATG13_CNT                 0
CWC_CATG2_CNT                  0
CWC_CATG3_CNT                  0
CWC_CATG4_CNT                  0
CWC_CATG5_CNT                  0
CWC_CATG6_CNT                  0
CWC_CATG7_CNT                  0
CWC_CATG8_CNT                  0
CWC_CATG9_CNT                  0
SELFCARE_IND                   0
LAST_CHANNEL_TYPE              0
AVG_HS_USE_MONTH_EX_CURR       0
HS_LEASE_FEATURE_NAME          0
IMEI_MFG_NAME                  0
IMEI_MKT_NAME                  0
ACTV_TYPE                      0
AGE                            0
APPLY_CURR_EBILL_SBILL_FLAG    0
AUTOPAY_IND                    0
          

In [110]:
out_filename = "0814_marketing_with_picked_group11_with_id"
full_df.to_csv(out_filename + ".csv", index=False, encoding='utf-8')

In [111]:
full_df.drop('MINING_DW_SUBSCR_NO', 1, inplace=True)

In [112]:
out_filename = "0814_marketing_with_picked_group11"
full_df.to_csv(out_filename + ".csv", index=False, encoding='utf-8')

In [90]:
cate_cols = []
num_cols = []
for c in full_df.columns:
    if full_df[c].dtype == np.object:
        cate_cols.append(c)
    else:
        num_cols.append(c)
num_cols.append('Groups')
        
print("-------------categorical columns------------")
print(cate_cols)
print("-------------numerical columns------------")
print(num_cols)

-------------categorical columns------------
['SELFCARE_IND', 'LAST_CHANNEL_TYPE', 'HS_LEASE_FEATURE_NAME', 'IMEI_MFG_NAME', 'IMEI_MKT_NAME', 'ACTV_TYPE', 'APPLY_CURR_EBILL_SBILL_FLAG', 'AUTOPAY_IND', 'BILL_ZIP_CODE', 'CHANNEL_CHURN_INDEX', 'CHURN_CLM_IND', 'CURR_DATA_BILL_PLAN_NAME', 'CURR_PROM_COMMIT_MONTHS', 'CUST_TYPE', 'FETNET_IND', 'FLAT_RATE_3G_IND', 'FLAT_RATE_4G_IND', 'GA_IND', 'GENDER_CODE', 'GOOGLE_PLAY_IND', 'HAPPYGO_IND', 'MDS_CURR_RENEW_TYPE', 'MSISDN_LAST_NP_OUT_IND', 'NP_IN_IND', 'ORIG_OPR_ID', 'PAY_PENALTY_FLAG', 'PROM_CURR_PROMOTION_SUB_TYPE', 'PROM_CURR_PROMOTION_TYPE', 'PROM_FLAT_RATE_4G_IND', 'SERVICE_STATUS_MOVIE_FLAG', 'SERVICE_STATUS_OMUSIC_FLAG', 'SERVICE_STATUS_READING_FLAG', 'SRV_TYPE_DESC', 'VIP_GRADE', 'VIP_REDEEM_IND', 'ZONE_ACTIVATION_IVR', 'DATA_BOOSTER_EVER_USE_FLAG', 'MOST_MO_OPERATOR', 'MOST_MT_OPERATOR', 'Groups']
-------------numerical columns------------
['BOOSTER_AMT', 'L3M_AVG_NET_INV_AMT', 'L3M_AVG_SMS_INV_AMT', 'PAY_PENALTY_AMT', 'TOTAL_MONTHLY

In [96]:
full_df

BOOSTER_AMT  L3M_AVG_NET_INV_AMT  L3M_AVG_SMS_INV_AMT  \
0                0.0               501.77                 0.00   
1                0.0              1441.63                 0.00   
2                0.0               703.14                 0.00   
3                0.0               715.16                 0.00   
4                0.0               673.72                 0.87   
5                0.0              1444.92                 0.00   
6                0.0               504.00                 0.00   
7                0.0              1120.10                 0.00   
8                0.0               771.26                 0.00   
9                0.0               299.00                 0.00   
10               0.0               149.00                 0.00   
11               0.0              1020.47                 0.00   
12               0.0               528.27                 0.00   
13               0.0              1311.39                 6.09   
14               0.0              1856.23                 0.00   
15               0.0              1446.37                 0.00   
16               0.0              1310.55                 0.00   
17               0.0              1114.64                 1.74   
18               0.0              1012.47                 0.00   
19               0.0                49.00                 0.00   
20               0.0              1204.24                 0.00   
21               0.0              1433.62                 0.00   
22               0.0              1213.57                 0.00   
23               0.0               796.99                 0.00   
24               0.0               636.33                 0.00   
25               0.0              1018.97                 0.87   
26               0.0               729.66                 0.00   
27               0.0              2749.95                 7.84   
28               0.0              1296.74                 0.87   
29               0.0               707.92                 0.00   
...              ...                  ...                  ...   
1811915          0.0              1493.67                 0.00   
1811916          0.0              1298.10                 0.00   
1811917          0.0               702.60                 0.00   
1811918          0.0               836.52                 0.00   
1811919          0.0               599.75                 0.00   
1811920          0.0               599.00                 0.00   
1811921          0.0              1441.37                 0.00   
1811922          0.0               656.99                 2.61   
1811923          0.0              1689.50                 0.00   
1811924          0.0              1000.33                 0.00   
1811925          0.0              1411.16                 8.71   
1811926          0.0              1609.17                 0.00   
1811927          0.0               532.07                 0.00   
1811928          0.0               811.40                 0.00   
1811929          0.0              1423.47                 0.00   
1811930          0.0               599.00                 0.00   
1811931          0.0              1978.56                 0.00   
1811932          0.0               336.81                 0.87   
1811933          0.0               526.00                 0.00   
1811934          0.0               714.19                 0.00   
1811935          0.0               803.97                 0.00   
1811936          0.0               599.00                 0.00   
1811937          0.0              2465.23                13.82   
1811938          0.0              1007.44                 0.00   
1811939          0.0               310.63                 0.00   
1811940          0.0              1328.03                 0.00   
1811941          0.0               865.87                 4.35   
1811942          0.0               700.26                 0.00   
1811943          0.0               309.71        

In [92]:
full_cate_df = full_df[cate_cols]
full_num_df = full_df[num_cols]

In [93]:
full_cate_df

SELFCARE_IND LAST_CHANNEL_TYPE HS_LEASE_FEATURE_NAME  \
0                  N            Retail                     ?   
1                  N         Franchise                     ?   
2                  N         Franchise                     ?   
3                  N            Retail                     ?   
4                  N           Loyalty                     ?   
5                  N                WS                     ?   
6                  N           Loyalty                     ?   
7                  N            Retail                     ?   
8                  N                WS                     ?   
9                  N         Franchise                     ?   
10                 N           Loyalty                     ?   
11                 Y         Franchise                     ?   
12                 N            Retail                     ?   
13                 N            Retail                     ?   
14                 N         Franchise                     ?   
15                 N            Retail                     ?   
16                 N           Loyalty                     ?   
17                 Y            Retail                     ?   
18                 N                WS                     ?   
19                 Y           Loyalty                     ?   
20                 N         Franchise                     ?   
21                 N            Others                     ?   
22                 N         Franchise                     ?   
23                 N            Retail    POS3RV 遠傳金機救援99月租費   
24                 N            Retail                     ?   
25                 Y         Franchise                     ?   
26                 N                WS                     ?   
27                 N          Indirect                     ?   
28                 N            Retail   POS3RV 遠傳金機救援249月租費   
29                 N            Retail                     ?   
...              ...               ...                   ...   
1811915            N                WS                     ?   
1811916            N            Retail   POS3RV 遠傳金機救援199月租費   
1811917            N            Retail                     ?   
1811918            N                WS                     ?   
1811919            N         Franchise                     ?   
1811920            N            Retail                     ?   
1811921            N            Retail                     ?   
1811922            Y            Retail                     ?   
1811923            N         Franchise   POS3RV 遠傳金機救援249月租費   
1811924            N                WS                     ?   
1811925            Y            Retail                     ?   
1811926            N            Retail                     ?   
1811927            N                WS                     ?   
1811928            N            Retail                     ?   
1811929            N         Franchise                     ?   
1811930            N         Franchise                     ?   
1811931            N            Retail                     ?   
1811932            N            Estore                     ?   
1811933            N            Retail                     ?   
1811934            N          Indirect                     ?   
1811935            N            Retail                     ?   
1811936            N            Retail                     ?   
1811937            N                WS                     ?   
1811938            N         Franchise                     ?   
1811939            Y         Franchise                     ?   
1811940            N                WS                     ?   
1811941            Y                WS                     ?   
1811942            N            Retail                     ?   
1811943            N            Retail                     ?   
1811944            N                WS                     ?   

                                       

In [94]:
full_num_df

BOOSTER_AMT  L3M_AVG_NET_INV_AMT  L3M_AVG_SMS_INV_AMT  \
0                0.0               501.77                 0.00   
1                0.0              1441.63                 0.00   
2                0.0               703.14                 0.00   
3                0.0               715.16                 0.00   
4                0.0               673.72                 0.87   
5                0.0              1444.92                 0.00   
6                0.0               504.00                 0.00   
7                0.0              1120.10                 0.00   
8                0.0               771.26                 0.00   
9                0.0               299.00                 0.00   
10               0.0               149.00                 0.00   
11               0.0              1020.47                 0.00   
12               0.0               528.27                 0.00   
13               0.0              1311.39                 6.09   
14               0.0              1856.23                 0.00   
15               0.0              1446.37                 0.00   
16               0.0              1310.55                 0.00   
17               0.0              1114.64                 1.74   
18               0.0              1012.47                 0.00   
19               0.0                49.00                 0.00   
20               0.0              1204.24                 0.00   
21               0.0              1433.62                 0.00   
22               0.0              1213.57                 0.00   
23               0.0               796.99                 0.00   
24               0.0               636.33                 0.00   
25               0.0              1018.97                 0.87   
26               0.0               729.66                 0.00   
27               0.0              2749.95                 7.84   
28               0.0              1296.74                 0.87   
29               0.0               707.92                 0.00   
...              ...                  ...                  ...   
1811915          0.0              1493.67                 0.00   
1811916          0.0              1298.10                 0.00   
1811917          0.0               702.60                 0.00   
1811918          0.0               836.52                 0.00   
1811919          0.0               599.75                 0.00   
1811920          0.0               599.00                 0.00   
1811921          0.0              1441.37                 0.00   
1811922          0.0               656.99                 2.61   
1811923          0.0              1689.50                 0.00   
1811924          0.0              1000.33                 0.00   
1811925          0.0              1411.16                 8.71   
1811926          0.0              1609.17                 0.00   
1811927          0.0               532.07                 0.00   
1811928          0.0               811.40                 0.00   
1811929          0.0              1423.47                 0.00   
1811930          0.0               599.00                 0.00   
1811931          0.0              1978.56                 0.00   
1811932          0.0               336.81                 0.87   
1811933          0.0               526.00                 0.00   
1811934          0.0               714.19                 0.00   
1811935          0.0               803.97                 0.00   
1811936          0.0               599.00                 0.00   
1811937          0.0              2465.23                13.82   
1811938          0.0              1007.44                 0.00   
1811939          0.0               310.63                 0.00   
1811940          0.0              1328.03                 0.00   
1811941          0.0               865.87                 4.35   
1811942          0.0               700.26                 0.00   
1811943          0.0               309.71        

In [3]:
test = pd.DataFrame()
test['test'] = ['a', 'b', 'c']
test['test1'] = 'tt'
test1 = pd.DataFrame()
test1 = test1.append(test)
test1 = test1.append(test)
test1

test test1
0    a    tt
1    b    tt
2    c    tt
0    a    tt
1    b    tt
2    c    tt

In [4]:
test1.index = list(range(len(test1)))

In [7]:
test1

test test1
0    a    tt
1    b    tt
2    c    tt
3    a    tt
4    b    tt
5    c    tt

In [8]:
from sklearn.utils import shuffle

In [11]:
test1 = shuffle(test1)

In [12]:
test1

test test1
2    c    tt
0    a    tt
4    b    tt
3    a    tt
5    c    tt
1    b    tt

In [13]:
start_time = time()

path = 'D:/0814_sample_SMOTE/Adult/'
filename = '0814_marketing_with_picked_group11_numeric_max_min_sample_Adult_others.csv'

# cols = ['P3M_AVG_DATA_USAGE_MB', 'DATA_USAGE_MB', 'IMEI_MFG_NAME', 'L3M_DATA_USAGE_MB', 'IMEI_MKT_NAME', 'AGE', 'GENDER_CODE', 'DATA_MONTHLY_FEE', 'L3M_AVG_NET_INV_AMT', 'TOTAL_MONTHLY_FEE', 'L3M_NET_INV_AMT', 'PROM_CURR_PROMOTION_TYPE', 'DATA_INV_AMT', 'MOST_MT_OPERATOR', 'VOICE_INV_AMT', 'LAST_CHANNEL_TYPE', 'TENURE_SCV', 'BILL_CITY_NAME', 'BILL_ZIP_CODE', 'ACTV_STORE_ID', 'MOST_MO_OPERATOR', 'CURR_DATA_BILL_PLAN_NAME', 'BL_CYCLE_DESC', 'ZONE_ACTIVATION_IVR', 'MOC_TWM_CNT', 'P3M_MO_PSTN_CNT', 'MTC_TWM_CNT', 'PSTN_CNT', 'MTC_CHM_CNT', 'MOC_CHM_CNT', 'MOC_PSTN_CNT', 'MTC_PSTN_CNT', 'MT_PSTN_CNT', 'HS_CHG_CNT', 'SMS_PROM_IND', 'MTC_APT_CNT', 'L3M_AVG_SMS_INV_AMT', 'MULTI_SIM_INCLUDE_WBB', 'MOC_APT_CNT', 'MTC_DUR', 'MOC_TSC_CNT', 'MTC_TSC_CNT', 'PROM_FLAT_RATE_4G_IND', 'FLAT_RATE_4G_IND', 'MT_TTL_DURATION', 'MO_TTL_DURATION', 'MT_OFFNET_DUR', 'MT_ONNET_DUR', 'MTC_PSTN_DUR']

df = pd.read_csv(path + filename, error_bad_lines=False)

print('load csv %s seconds', format(time() - start_time))

load csv %s seconds 61.812063217163086


In [14]:
df['Groups'].value_counts()

Adult     1763660
Others    1763660
Name: Groups, dtype: int64